name: Build and Deploy

env:
  ANYPOINT_CLIENT_ID: ${{ secrets.APM_CLIENT_ID }}
  ANYPOINT_CLIENT_SECRET: ${{ secrets.APM_CLIENT_SECRET }}
  CONNECTED_APP_STRING: ${{ secrets.CONNECTED_APP_STRING }}
  CONNECTED_APP_CLIENT_ID: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
  CONNECTED_APP_CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
  GRANT_TYPE: ${{ vars.GRANT_TYPE }}
  PAT: ${{ secrets.PAT }}
  TARGET: ${{ vars.TARGET }}
  ENVIRONMENT: "${{ inputs.environment }}"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Enter the repository name'
        required: true
        type: string
      environment:
        description: "Deployment Environment"
        required: true
        type: choice
        options:
          - DEV
      vCore:
        description: "vCore on Deployment Target"
        required: true
        type: choice
        options:
          - "0.1"
          - "0.2"
          - "0.5"
          - "1"
      replicas:
        description: "Number of Replicas on Deployment Target"
        required: true
        type: choice
        options:
          - "1"
          - "2"

run-name: "Deploying ${{ inputs.repository }} to ${{ inputs.environment }}"

jobs:
  Deploy-to-CloudHub:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Maven 3.9.9
        uses: s4u/setup-maven-action@v1.12.0
        with:
          java-version: 17
          maven-version: 3.9.9
          
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository_owner }}/${{ inputs.repository }}'
          ref: '${{ inputs.branch }}'
          token: "${{ env.PAT }}"
          fetch-depth: 0

      - name: Configure Maven settings
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: >
            [
              {
                "id": "anypoint-exchange-v3",
                "username": "~~~Client~~~",
                "password": "${{ env.CONNECTED_APP_STRING }}"
              }
            ] 
          repositories: >
            [
              {
                "id": "anypoint-exchange-v3",
                "url": "https://maven.anypoint.mulesoft.com/api/v3/maven",
                "releases": { "enabled": "true" },
                "snapshots": { "enabled": "true" }
              }
            ]

      - name: Set App Tag
        run: |
          MULE_ENV=$(echo '${{ inputs.environment }}' | tr '[:upper:]' '[:lower:]')
          if [[ "$MULE_ENV" == "dev" ]]; then
            echo "APP_TAG=-$MULE_ENV" >> $GITHUB_ENV
          else
            echo "APP_TAG=" >> $GITHUB_ENV
          fi

      - name: Publish Artifact to Anypoint Exchange
        run: |
          mvn clean deploy -DskipTests \
          -D"mule.env"="${{ env.ENVIRONMENT }}" \
          -D"app.vCores"="${{ inputs.vCore }}" \
          -D"app.replicas"="${{ inputs.replicas }}" \
          -D"app.url.env"="${{ env.APP_TAG }}" \
          -D"anypoint.privatespace.name"="${{ env.TARGET }}" \
          -D"connectedAppClientId"="${{ env.CONNECTED_APP_CLIENT_ID }}" \
          -D"connectedAppClientSecret"="${{ env.CONNECTED_APP_CLIENT_SECRET }}" \
          -D"connectedAppGrantType"="${{ env.GRANT_TYPE }}" \
          -D"anypoint.platform.client_id"="${{ env.ANYPOINT_CLIENT_ID }}" \
          -D"anypoint.platform.client_secret"="${{ env.ANYPOINT_CLIENT_SECRET }}"

      - name: Upload Artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.repository }}-${{ inputs.environment }}-jar
          path: target/*.jar
          retention-days: 14

      - name: Deploy Application to CloudHub 2.0
        run: |
          mvn mule:deploy -DskipTests \
          -D"mule.env"="${{ env.ENVIRONMENT }}" \
          -D"app.vCores"="${{ inputs.vCore }}" \
          -D"app.replicas"="${{ inputs.replicas }}" \
          -D"app.url.env"="${{ env.APP_TAG }}" \
          -D"anypoint.privatespace.name"="${{ env.TARGET }}" \
          -D"connectedAppClientId"="${{ env.CONNECTED_APP_CLIENT_ID }}" \
          -D"connectedAppClientSecret"="${{ env.CONNECTED_APP_CLIENT_SECRET }}" \
          -D"connectedAppGrantType"="${{ env.GRANT_TYPE }}" \
          -D"anypoint.platform.client_id"="${{ env.ANYPOINT_CLIENT_ID }}" \
          -D"anypoint.platform.client_secret"="${{ env.ANYPOINT_CLIENT_SECRET }}"